// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: protos/doc_store.proto

package docstoreAPI

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// document and payload for it
type PutRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CollectionName string                 `protobuf:"bytes,1,opt,name=collection_name,json=collectionName,proto3" json:"collection_name,omitempty"`
	DocId          string                 `protobuf:"bytes,2,opt,name=doc_id,json=docId,proto3" json:"doc_id,omitempty"`
	Payload        []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PutRequest) Reset() {
	*x = PutRequest{}
	mi := &file_protos_doc_store_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutRequest) ProtoMessage() {}

func (x *PutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_doc_store_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutRequest.ProtoReflect.Descriptor instead.
func (*PutRequest) Descriptor() ([]byte, []int) {
	return file_protos_doc_store_proto_rawDescGZIP(), []int{0}
}

func (x *PutRequest) GetCollectionName() string {
	if x != nil {
		return x.CollectionName
	}
	return ""
}

func (x *PutRequest) GetDocId() string {
	if x != nil {
		return x.DocId
	}
	return ""
}

func (x *PutRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// id of the downloaded document
type PutResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CollectionName string                 `protobuf:"bytes,1,opt,name=collection_name,json=collectionName,proto3" json:"collection_name,omitempty"`
	DocId          string                 `protobuf:"bytes,2,opt,name=doc_id,json=docId,proto3" json:"doc_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PutResponse) Reset() {
	*x = PutResponse{}
	mi := &file_protos_doc_store_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutResponse) ProtoMessage() {}

func (x *PutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_doc_store_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutResponse.ProtoReflect.Descriptor instead.
func (*PutResponse) Descriptor() ([]byte, []int) {
	return file_protos_doc_store_proto_rawDescGZIP(), []int{1}
}

func (x *PutResponse) GetCollectionName() string {
	if x != nil {
		return x.CollectionName
	}
	return ""
}

func (x *PutResponse) GetDocId() string {
	if x != nil {
		return x.DocId
	}
	return ""
}

// id of the document to delete
type DeleteRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CollectionName string                 `protobuf:"bytes,1,opt,name=collection_name,json=collectionName,proto3" json:"collection_name,omitempty"`
	DocId          string                 `protobuf:"bytes,2,opt,name=doc_id,json=docId,proto3" json:"doc_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_protos_doc_store_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_doc_store_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_protos_doc_store_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteRequest) GetCollectionName() string {
	if x != nil {
		return x.CollectionName
	}
	return ""
}

func (x *DeleteRequest) GetDocId() string {
	if x != nil {
		return x.DocId
	}
	return ""
}

// id of the deleted document
type DeleteResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CollectionName string                 `protobuf:"bytes,1,opt,name=collection_name,json=collectionName,proto3" json:"collection_name,omitempty"`
	DocId          string                 `protobuf:"bytes,2,opt,name=doc_id,json=docId,proto3" json:"doc_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_protos_doc_store_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_doc_store_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_protos_doc_store_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteResponse) GetCollectionName() string {
	if x != nil {
		return x.CollectionName
	}
	return ""
}

func (x *DeleteResponse) GetDocId() string {
	if x != nil {
		return x.DocId
	}
	return ""
}

// id of the document to get
type GetRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CollectionName string                 `protobuf:"bytes,1,opt,name=collection_name,json=collectionName,proto3" json:"collection_name,omitempty"`
	DocId          string                 `protobuf:"bytes,2,opt,name=doc_id,json=docId,proto3" json:"doc_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_protos_doc_store_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_doc_store_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_protos_doc_store_proto_rawDescGZIP(), []int{4}
}

func (x *GetRequest) GetCollectionName() string {
	if x != nil {
		return x.CollectionName
	}
	return ""
}

func (x *GetRequest) GetDocId() string {
	if x != nil {
		return x.DocId
	}
	return ""
}

// payload of the retrieved document
type GetResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CollectionName string                 `protobuf:"bytes,1,opt,name=collection_name,json=collectionName,proto3" json:"collection_name,omitempty"`
	DocId          string                 `protobuf:"bytes,2,opt,name=doc_id,json=docId,proto3" json:"doc_id,omitempty"`
	Payload        []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_protos_doc_store_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_doc_store_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_protos_doc_store_proto_rawDescGZIP(), []int{5}
}

func (x *GetResponse) GetCollectionName() string {
	if x != nil {
		return x.CollectionName
	}
	return ""
}

func (x *GetResponse) GetDocId() string {
	if x != nil {
		return x.DocId
	}
	return ""
}

func (x *GetResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_protos_doc_store_proto protoreflect.FileDescriptor

const file_protos_doc_store_proto_rawDesc = "" +
	"\n" +
	"\x16protos/doc_store.proto\x12\rdoc_store_api\"f\n" +
	"\n" +
	"PutRequest\x12'\n" +
	"\x0fcollection_name\x18\x01 \x01(\tR\x0ecollectionName\x12\x15\n" +
	"\x06doc_id\x18\x02 \x01(\tR\x05docId\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\"M\n" +
	"\vPutResponse\x12'\n" +
	"\x0fcollection_name\x18\x01 \x01(\tR\x0ecollectionName\x12\x15\n" +
	"\x06doc_id\x18\x02 \x01(\tR\x05docId\"O\n" +
	"\rDeleteRequest\x12'\n" +
	"\x0fcollection_name\x18\x01 \x01(\tR\x0ecollectionName\x12\x15\n" +
	"\x06doc_id\x18\x02 \x01(\tR\x05docId\"P\n" +
	"\x0eDeleteResponse\x12'\n" +
	"\x0fcollection_name\x18\x01 \x01(\tR\x0ecollectionName\x12\x15\n" +
	"\x06doc_id\x18\x02 \x01(\tR\x05docId\"L\n" +
	"\n" +
	"GetRequest\x12'\n" +
	"\x0fcollection_name\x18\x01 \x01(\tR\x0ecollectionName\x12\x15\n" +
	"\x06doc_id\x18\x02 \x01(\tR\x05docId\"g\n" +
	"\vGetResponse\x12'\n" +
	"\x0fcollection_name\x18\x01 \x01(\tR\x0ecollectionName\x12\x15\n" +
	"\x06doc_id\x18\x02 \x01(\tR\x05docId\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload2\xea\x01\n" +
	"\rDocumentStore\x12D\n" +
	"\vPutDocument\x12\x19.doc_store_api.PutRequest\x1a\x1a.doc_store_api.PutResponse\x12M\n" +
	"\x0eDeleteDocument\x12\x1c.doc_store_api.DeleteRequest\x1a\x1d.doc_store_api.DeleteResponse\x12D\n" +
	"\vGetDocument\x12\x19.doc_store_api.GetRequest\x1a\x1a.doc_store_api.GetResponseB=Z;github.com/VlanAni/nosql_over_postgres/internal/docstoreAPIb\x06proto3"

var (
	file_protos_doc_store_proto_rawDescOnce sync.Once
	file_protos_doc_store_proto_rawDescData []byte
)

func file_protos_doc_store_proto_rawDescGZIP() []byte {
	file_protos_doc_store_proto_rawDescOnce.Do(func() {
		file_protos_doc_store_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_doc_store_proto_rawDesc), len(file_protos_doc_store_proto_rawDesc)))
	})
	return file_protos_doc_store_proto_rawDescData
}

var file_protos_doc_store_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_protos_doc_store_proto_goTypes = []any{
	(*PutRequest)(nil),     // 0: doc_store_api.PutRequest
	(*PutResponse)(nil),    // 1: doc_store_api.PutResponse
	(*DeleteRequest)(nil),  // 2: doc_store_api.DeleteRequest
	(*DeleteResponse)(nil), // 3: doc_store_api.DeleteResponse
	(*GetRequest)(nil),     // 4: doc_store_api.GetRequest
	(*GetResponse)(nil),    // 5: doc_store_api.GetResponse
}
var file_protos_doc_store_proto_depIdxs = []int32{
	0, // 0: doc_store_api.DocumentStore.PutDocument:input_type -> doc_store_api.PutRequest
	2, // 1: doc_store_api.DocumentStore.DeleteDocument:input_type -> doc_store_api.DeleteRequest
	4, // 2: doc_store_api.DocumentStore.GetDocument:input_type -> doc_store_api.GetRequest
	1, // 3: doc_store_api.DocumentStore.PutDocument:output_type -> doc_store_api.PutResponse
	3, // 4: doc_store_api.DocumentStore.DeleteDocument:output_type -> doc_store_api.DeleteResponse
	5, // 5: doc_store_api.DocumentStore.GetDocument:output_type -> doc_store_api.GetResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protos_doc_store_proto_init() }
func file_protos_doc_store_proto_init() {
	if File_protos_doc_store_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_doc_store_proto_rawDesc), len(file_protos_doc_store_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_doc_store_proto_goTypes,
		DependencyIndexes: file_protos_doc_store_proto_depIdxs,
		MessageInfos:      file_protos_doc_store_proto_msgTypes,
	}.Build()
	File_protos_doc_store_proto = out.File
	file_protos_doc_store_proto_goTypes = nil
	file_protos_doc_store_proto_depIdxs = nil
}
