// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: doc_store.proto

package docstoreAPI

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// doc_name - имя создаваемой сущности
// description - json-объект описание полей и типов
type CreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocName       string                 `protobuf:"bytes,1,opt,name=doc_name,json=docName,proto3" json:"doc_name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRequest) Reset() {
	*x = CreateRequest{}
	mi := &file_doc_store_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequest) ProtoMessage() {}

func (x *CreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_doc_store_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequest.ProtoReflect.Descriptor instead.
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return file_doc_store_proto_rawDescGZIP(), []int{0}
}

func (x *CreateRequest) GetDocName() string {
	if x != nil {
		return x.DocName
	}
	return ""
}

func (x *CreateRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// doc_name - имя сущности
// success - булевый результат операции
type CreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocName       string                 `protobuf:"bytes,1,opt,name=doc_name,json=docName,proto3" json:"doc_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateResponse) Reset() {
	*x = CreateResponse{}
	mi := &file_doc_store_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResponse) ProtoMessage() {}

func (x *CreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_doc_store_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResponse.ProtoReflect.Descriptor instead.
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return file_doc_store_proto_rawDescGZIP(), []int{1}
}

func (x *CreateResponse) GetDocName() string {
	if x != nil {
		return x.DocName
	}
	return ""
}

// doc_name - имя сущности (для маршрутизации по таблицам)
// item - json-сущность с конкретными значениями
type InsertRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocName       string                 `protobuf:"bytes,1,opt,name=doc_name,json=docName,proto3" json:"doc_name,omitempty"`
	Item          string                 `protobuf:"bytes,2,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertRequest) Reset() {
	*x = InsertRequest{}
	mi := &file_doc_store_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertRequest) ProtoMessage() {}

func (x *InsertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_doc_store_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertRequest.ProtoReflect.Descriptor instead.
func (*InsertRequest) Descriptor() ([]byte, []int) {
	return file_doc_store_proto_rawDescGZIP(), []int{2}
}

func (x *InsertRequest) GetDocName() string {
	if x != nil {
		return x.DocName
	}
	return ""
}

func (x *InsertRequest) GetItem() string {
	if x != nil {
		return x.Item
	}
	return ""
}

// doc_name - имя сущности
// success - успех или неуспех операциии
// id - идентификатор вставленного элемента (string выбрал для универсальности)
type InsertResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocName       string                 `protobuf:"bytes,1,opt,name=doc_name,json=docName,proto3" json:"doc_name,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertResponse) Reset() {
	*x = InsertResponse{}
	mi := &file_doc_store_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertResponse) ProtoMessage() {}

func (x *InsertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_doc_store_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertResponse.ProtoReflect.Descriptor instead.
func (*InsertResponse) Descriptor() ([]byte, []int) {
	return file_doc_store_proto_rawDescGZIP(), []int{3}
}

func (x *InsertResponse) GetDocName() string {
	if x != nil {
		return x.DocName
	}
	return ""
}

func (x *InsertResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// doc_name - имя документа
// requirements - json-строка с полями и значениями полей, по которым нужно фильтровать
type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocName       string                 `protobuf:"bytes,1,opt,name=doc_name,json=docName,proto3" json:"doc_name,omitempty"`
	Requirements  string                 `protobuf:"bytes,2,opt,name=requirements,proto3" json:"requirements,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_doc_store_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_doc_store_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_doc_store_proto_rawDescGZIP(), []int{4}
}

func (x *GetRequest) GetDocName() string {
	if x != nil {
		return x.DocName
	}
	return ""
}

func (x *GetRequest) GetRequirements() string {
	if x != nil {
		return x.Requirements
	}
	return ""
}

// doc_name - имя документа
// success - результат операции
// items - список json-ов документов
type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocName       string                 `protobuf:"bytes,1,opt,name=doc_name,json=docName,proto3" json:"doc_name,omitempty"`
	Items         []string               `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_doc_store_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_doc_store_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_doc_store_proto_rawDescGZIP(), []int{5}
}

func (x *GetResponse) GetDocName() string {
	if x != nil {
		return x.DocName
	}
	return ""
}

func (x *GetResponse) GetItems() []string {
	if x != nil {
		return x.Items
	}
	return nil
}

// doc_name - имя документа
// target - json-строка с полями и значениями полей, по которым нужно удалять элементы
type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocName       string                 `protobuf:"bytes,1,opt,name=doc_name,json=docName,proto3" json:"doc_name,omitempty"`
	Target        string                 `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_doc_store_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_doc_store_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_doc_store_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteRequest) GetDocName() string {
	if x != nil {
		return x.DocName
	}
	return ""
}

func (x *DeleteRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

// doc_name - имя документа
// success - результат операции
// ids - список id удалённых документов
type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocName       string                 `protobuf:"bytes,1,opt,name=doc_name,json=docName,proto3" json:"doc_name,omitempty"`
	Ids           []string               `protobuf:"bytes,2,rep,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_doc_store_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_doc_store_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_doc_store_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteResponse) GetDocName() string {
	if x != nil {
		return x.DocName
	}
	return ""
}

func (x *DeleteResponse) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

var File_doc_store_proto protoreflect.FileDescriptor

const file_doc_store_proto_rawDesc = "" +
	"\n" +
	"\x0fdoc_store.proto\x12\rdoc_store_api\"L\n" +
	"\rCreateRequest\x12\x19\n" +
	"\bdoc_name\x18\x01 \x01(\tR\adocName\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"+\n" +
	"\x0eCreateResponse\x12\x19\n" +
	"\bdoc_name\x18\x01 \x01(\tR\adocName\">\n" +
	"\rInsertRequest\x12\x19\n" +
	"\bdoc_name\x18\x01 \x01(\tR\adocName\x12\x12\n" +
	"\x04item\x18\x02 \x01(\tR\x04item\";\n" +
	"\x0eInsertResponse\x12\x19\n" +
	"\bdoc_name\x18\x01 \x01(\tR\adocName\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"K\n" +
	"\n" +
	"GetRequest\x12\x19\n" +
	"\bdoc_name\x18\x01 \x01(\tR\adocName\x12\"\n" +
	"\frequirements\x18\x02 \x01(\tR\frequirements\">\n" +
	"\vGetResponse\x12\x19\n" +
	"\bdoc_name\x18\x01 \x01(\tR\adocName\x12\x14\n" +
	"\x05items\x18\x02 \x03(\tR\x05items\"B\n" +
	"\rDeleteRequest\x12\x19\n" +
	"\bdoc_name\x18\x01 \x01(\tR\adocName\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06target\"=\n" +
	"\x0eDeleteResponse\x12\x19\n" +
	"\bdoc_name\x18\x01 \x01(\tR\adocName\x12\x10\n" +
	"\x03ids\x18\x02 \x03(\tR\x03ids2\xc2\x02\n" +
	"\rDocumentStore\x12M\n" +
	"\x0eCreateDocument\x12\x1c.doc_store_api.CreateRequest\x1a\x1d.doc_store_api.CreateResponse\x12M\n" +
	"\x0eInsertDocument\x12\x1c.doc_store_api.InsertRequest\x1a\x1d.doc_store_api.InsertResponse\x12D\n" +
	"\vGetDocument\x12\x19.doc_store_api.GetRequest\x1a\x1a.doc_store_api.GetResponse\x12M\n" +
	"\x0eDeleteDocument\x12\x1c.doc_store_api.DeleteRequest\x1a\x1d.doc_store_api.DeleteResponseB=Z;github.com/VlanAni/nosql_over_postgres/internal/docstoreAPIb\x06proto3"

var (
	file_doc_store_proto_rawDescOnce sync.Once
	file_doc_store_proto_rawDescData []byte
)

func file_doc_store_proto_rawDescGZIP() []byte {
	file_doc_store_proto_rawDescOnce.Do(func() {
		file_doc_store_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_doc_store_proto_rawDesc), len(file_doc_store_proto_rawDesc)))
	})
	return file_doc_store_proto_rawDescData
}

var file_doc_store_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_doc_store_proto_goTypes = []any{
	(*CreateRequest)(nil),  // 0: doc_store_api.CreateRequest
	(*CreateResponse)(nil), // 1: doc_store_api.CreateResponse
	(*InsertRequest)(nil),  // 2: doc_store_api.InsertRequest
	(*InsertResponse)(nil), // 3: doc_store_api.InsertResponse
	(*GetRequest)(nil),     // 4: doc_store_api.GetRequest
	(*GetResponse)(nil),    // 5: doc_store_api.GetResponse
	(*DeleteRequest)(nil),  // 6: doc_store_api.DeleteRequest
	(*DeleteResponse)(nil), // 7: doc_store_api.DeleteResponse
}
var file_doc_store_proto_depIdxs = []int32{
	0, // 0: doc_store_api.DocumentStore.CreateDocument:input_type -> doc_store_api.CreateRequest
	2, // 1: doc_store_api.DocumentStore.InsertDocument:input_type -> doc_store_api.InsertRequest
	4, // 2: doc_store_api.DocumentStore.GetDocument:input_type -> doc_store_api.GetRequest
	6, // 3: doc_store_api.DocumentStore.DeleteDocument:input_type -> doc_store_api.DeleteRequest
	1, // 4: doc_store_api.DocumentStore.CreateDocument:output_type -> doc_store_api.CreateResponse
	3, // 5: doc_store_api.DocumentStore.InsertDocument:output_type -> doc_store_api.InsertResponse
	5, // 6: doc_store_api.DocumentStore.GetDocument:output_type -> doc_store_api.GetResponse
	7, // 7: doc_store_api.DocumentStore.DeleteDocument:output_type -> doc_store_api.DeleteResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_doc_store_proto_init() }
func file_doc_store_proto_init() {
	if File_doc_store_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_doc_store_proto_rawDesc), len(file_doc_store_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_doc_store_proto_goTypes,
		DependencyIndexes: file_doc_store_proto_depIdxs,
		MessageInfos:      file_doc_store_proto_msgTypes,
	}.Build()
	File_doc_store_proto = out.File
	file_doc_store_proto_goTypes = nil
	file_doc_store_proto_depIdxs = nil
}
