// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: protos/doc_store.proto

package docstoreAPI

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DocumentStore_PutDocument_FullMethodName    = "/doc_store_api.DocumentStore/PutDocument"
	DocumentStore_DeleteDocument_FullMethodName = "/doc_store_api.DocumentStore/DeleteDocument"
	DocumentStore_GetDocument_FullMethodName    = "/doc_store_api.DocumentStore/GetDocument"
)

// DocumentStoreClient is the client API for DocumentStore service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DocumentStoreClient interface {
	PutDocument(ctx context.Context, in *PutRequest, opts ...grpc.CallOption) (*PutResponse, error)
	DeleteDocument(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	GetDocument(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
}

type documentStoreClient struct {
	cc grpc.ClientConnInterface
}

func NewDocumentStoreClient(cc grpc.ClientConnInterface) DocumentStoreClient {
	return &documentStoreClient{cc}
}

func (c *documentStoreClient) PutDocument(ctx context.Context, in *PutRequest, opts ...grpc.CallOption) (*PutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PutResponse)
	err := c.cc.Invoke(ctx, DocumentStore_PutDocument_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentStoreClient) DeleteDocument(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, DocumentStore_DeleteDocument_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentStoreClient) GetDocument(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, DocumentStore_GetDocument_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DocumentStoreServer is the server API for DocumentStore service.
// All implementations must embed UnimplementedDocumentStoreServer
// for forward compatibility.
type DocumentStoreServer interface {
	PutDocument(context.Context, *PutRequest) (*PutResponse, error)
	DeleteDocument(context.Context, *DeleteRequest) (*DeleteResponse, error)
	GetDocument(context.Context, *GetRequest) (*GetResponse, error)
	mustEmbedUnimplementedDocumentStoreServer()
}

// UnimplementedDocumentStoreServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDocumentStoreServer struct{}

func (UnimplementedDocumentStoreServer) PutDocument(context.Context, *PutRequest) (*PutResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PutDocument not implemented")
}
func (UnimplementedDocumentStoreServer) DeleteDocument(context.Context, *DeleteRequest) (*DeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteDocument not implemented")
}
func (UnimplementedDocumentStoreServer) GetDocument(context.Context, *GetRequest) (*GetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDocument not implemented")
}
func (UnimplementedDocumentStoreServer) mustEmbedUnimplementedDocumentStoreServer() {}
func (UnimplementedDocumentStoreServer) testEmbeddedByValue()                       {}

// UnsafeDocumentStoreServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DocumentStoreServer will
// result in compilation errors.
type UnsafeDocumentStoreServer interface {
	mustEmbedUnimplementedDocumentStoreServer()
}

func RegisterDocumentStoreServer(s grpc.ServiceRegistrar, srv DocumentStoreServer) {
	// If the following call panics, it indicates UnimplementedDocumentStoreServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DocumentStore_ServiceDesc, srv)
}

func _DocumentStore_PutDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentStoreServer).PutDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentStore_PutDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentStoreServer).PutDocument(ctx, req.(*PutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocumentStore_DeleteDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentStoreServer).DeleteDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentStore_DeleteDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentStoreServer).DeleteDocument(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocumentStore_GetDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentStoreServer).GetDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentStore_GetDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentStoreServer).GetDocument(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DocumentStore_ServiceDesc is the grpc.ServiceDesc for DocumentStore service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DocumentStore_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "doc_store_api.DocumentStore",
	HandlerType: (*DocumentStoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PutDocument",
			Handler:    _DocumentStore_PutDocument_Handler,
		},
		{
			MethodName: "DeleteDocument",
			Handler:    _DocumentStore_DeleteDocument_Handler,
		},
		{
			MethodName: "GetDocument",
			Handler:    _DocumentStore_GetDocument_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/doc_store.proto",
}
